#!/usr/bin/env node
// Regenerates report/merge-contention.md from the captured records in runs/.
//
// This script is the reproducibility contract in executable form: every number
// in the published report is derived here from a committed run record, so a
// reader can check the arithmetic without re-running an agent or trusting a
// figure that was typed in by hand. If a number in the report is not in a run
// record, this script cannot produce it — which is the point.

import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const runsDir = path.join(here, "..", "runs");

function fmt(n, digits = 2) {
  return Number(n).toFixed(digits);
}

async function loadRuns(arm) {
  const files = (await readdir(runsDir)).filter((f) => f.endsWith(".json"));
  const records = [];
  for (const file of files) {
    const record = JSON.parse(await readFile(path.join(runsDir, file), "utf8"));
    if (record.arm === arm) records.push({ file, ...record });
  }
  return records.sort((a, b) => a.result.config.writers - b.result.config.writers);
}

function mergeContentionReport(records) {
  if (records.length === 0) {
    return "# Merge contention\n\n**Not run.** No records in `bench/runs/` for this arm.\n";
  }

  const environments = [...new Set(records.map((r) => `${r.environment.platform}, node ${r.environment.node}`))];
  const commits = [...new Set(records.map((r) => r.environment.serverCommit ?? "unrecorded"))];

  const rows = records.map((r) => {
    const x = r.result;
    const expectedSerial = (x.config.writers * (x.config.writers + 1)) / 2;
    return (
      `| ${x.config.writers} | ${x.landed}/${x.config.writers} | ${x.totalAttempts} | ${expectedSerial} | ` +
      `${x.totalConflicts} | ${fmt(x.conflictRate, 3)} | ${fmt(x.landsPerSecond)} | ` +
      `${fmt(x.landLatencyMs.p50, 0)} | ${fmt(x.landLatencyMs.p95, 0)} | ${x.retriesPerWriter.max} |`
    );
  });

  const allMatchSerial = records.every(
    (r) => r.result.totalAttempts === (r.result.config.writers * (r.result.config.writers + 1)) / 2,
  );

  return `# Merge contention — arm 1 results

*Generated by \`bench/report/build-report.mjs\` from the run records in
[\`bench/runs/\`](../runs). Do not edit by hand: re-run the script.*

**Deterministic arm.** No model, no agent, no LLM call. N writers race to land on
one branch over the REST API, each rebasing and retrying when the base moves
under it — the MVP land model's own instruction to an agent (\`docs/pragmatic_mvp.md\`
§2.5). Writers touch **distinct paths**, so every conflict measured here is *ref
contention*, not a textual conflict.

Environment: ${environments.join("; ")}. Server commit(s): ${commits.join(", ")}.

| Writers | Landed | Attempts | N(N+1)/2 | Conflicts | Conflict rate | Lands/s | p50 land (ms) | p95 land (ms) | Max retries |
|---|---|---|---|---|---|---|---|---|---|
${rows.join("\n")}

## What this shows

**Total attempts track N(N+1)/2 exactly${allMatchSerial ? "" : " (except where noted above)"}.** That is the
signature of fully serialized land: writer *k* retries *k* times, so the work
done grows quadratically in the number of concurrent writers while the number of
lands grows linearly. Conflict rate converges on (N−1)/(N+1) for the same reason.
This is the first first-party measurement of the merge-bottleneck hypothesis in
this repo, and it is consistent with it: **the merge path is a serialization
point, and its cost under fan-out is superlinear.**

**Every writer lands.** Nothing is dropped, nothing deadlocks, and no writer is
starved beyond N−1 retries. The FF-guarded compare-and-swap is correct under
concurrency; it is *throughput* that degrades, not correctness.

## What this does not show, and should not be read as showing

- **This is not a comparison against GitHub.** ForgeMark-comparable numbers need
  the same workload run against a real forge; that is arm 2, and it is not run
  here. Nothing above licenses a claim that ADP is faster or slower than anything.
- **The retry loop has no backoff and no jitter**, and all writers start in the
  same millisecond. Real orchestrators would stagger. That makes the quadratic
  above an *upper bound* on contention cost, not a prediction of production
  behaviour — a deliberately adversarial arrangement, chosen because the
  optimistic one proves nothing.
- **Latency here is dominated by REST round-trips per attempt** (tree, commit,
  ref, proposal, merge — five calls), not by git object work. Read the latency
  column as "cost of a retry in this harness", not as "cost of a merge".
- **Single box, single Postgres, dev hardware.** Absolute throughput is not a
  capacity claim. The *shape* of the curve is the finding; the constants are not.

## What consumes this

Per the M2 readiness review, conflict-rate telemetry is a required input to two
open questions, not an optional extra:

- **A17 (contention avoided upstream).** If real orchestrators partition work so
  that ref-level contention is rare, this curve never gets exercised and the
  bottleneck lands elsewhere. The numbers here describe the cost *if* contention
  happens, which is what makes A17 an empirical question rather than a
  preference.
- **The M5 speculative-merge-batching gate**, which requires written
  justification citing M3/M4 telemetry. The quadratic attempt count is the
  argument such a justification would have to make — and it is now measurable
  rather than asserted. It is not on its own sufficient: A17 has to fail first.
`;
}

async function main() {
  const records = await loadRuns("merge-contention");
  const target = path.join(here, "merge-contention.md");
  await writeFile(target, mergeContentionReport(records));
  console.error(`wrote ${path.relative(process.cwd(), target)} from ${records.length} run record(s)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
