#!/usr/bin/env node
// Regenerates report/merge-contention.md from the captured records in runs/.
//
// This script is the reproducibility contract in executable form: every number
// in the published report is derived here from a committed run record, so a
// reader can check the arithmetic without re-running an agent or trusting a
// figure that was typed in by hand. If a number in the report is not in a run
// record, this script cannot produce it — which is the point.

import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const runsDir = path.join(here, "..", "runs");

function fmt(n, digits = 2) {
  return Number(n).toFixed(digits);
}

async function loadRuns(arm) {
  const files = (await readdir(runsDir)).filter((f) => f.endsWith(".json"));
  const records = [];
  for (const file of files) {
    const record = JSON.parse(await readFile(path.join(runsDir, file), "utf8"));
    if (record.arm === arm) records.push({ file, ...record });
  }
  if (arm === "merge-contention") return records.sort((a, b) => a.result.config.writers - b.result.config.writers);
  return records.sort((a, b) => (a.method + a.taskId + a.rep).localeCompare(b.method + b.taskId + b.rep));
}

function mergeContentionReport(records) {
  if (records.length === 0) {
    return "# Merge contention\n\n**Not run.** No records in `bench/runs/` for this arm.\n";
  }

  const environments = [...new Set(records.map((r) => `${r.environment.platform}, node ${r.environment.node}`))];
  const commits = [...new Set(records.map((r) => r.environment.serverCommit ?? "unrecorded"))];

  const rows = records.map((r) => {
    const x = r.result;
    const expectedSerial = (x.config.writers * (x.config.writers + 1)) / 2;
    return (
      `| ${x.config.writers} | ${x.landed}/${x.config.writers} | ${x.totalAttempts} | ${expectedSerial} | ` +
      `${x.totalConflicts} | ${fmt(x.conflictRate, 3)} | ${fmt(x.landsPerSecond)} | ` +
      `${fmt(x.landLatencyMs.p50, 0)} | ${fmt(x.landLatencyMs.p95, 0)} | ${x.retriesPerWriter.max} |`
    );
  });

  const allMatchSerial = records.every(
    (r) => r.result.totalAttempts === (r.result.config.writers * (r.result.config.writers + 1)) / 2,
  );

  return `# Merge contention — arm 1 results

*Generated by \`bench/report/build-report.mjs\` from the run records in
[\`bench/runs/\`](../runs). Do not edit by hand: re-run the script.*

**Deterministic arm.** No model, no agent, no LLM call. N writers race to land on
one branch over the REST API, each rebasing and retrying when the base moves
under it — the MVP land model's own instruction to an agent. Writers touch
**distinct paths**, so every conflict measured here is *ref contention*, not a
textual conflict.

Environment: ${environments.join("; ")}. Server commit(s): ${commits.join(", ")}.

| Writers | Landed | Attempts | N(N+1)/2 | Conflicts | Conflict rate | Lands/s | p50 land (ms) | p95 land (ms) | Max retries |
|---|---|---|---|---|---|---|---|---|---|
${rows.join("\n")}

## What this shows

**Total attempts track N(N+1)/2 exactly${allMatchSerial ? "" : " (except where noted above)"}.** That is the
signature of fully serialized land: writer *k* retries *k* times, so the work
done grows quadratically in the number of concurrent writers while the number of
lands grows linearly. Conflict rate converges on (N−1)/(N+1) for the same reason.
This is the first first-party measurement of the merge-bottleneck hypothesis in
this repo, and it is consistent with it: **the merge path is a serialization
point, and its cost under fan-out is superlinear.**

**Every writer lands.** Nothing is dropped, nothing deadlocks, and no writer is
starved beyond N−1 retries. The FF-guarded compare-and-swap is correct under
concurrency; it is *throughput* that degrades, not correctness.

## What this does not show, and should not be read as showing

- **This is not a comparison against GitHub.** ForgeMark-comparable numbers need
  the same workload run against a real forge — that is arm 2, published separately
  at [\`report/three-way-cost.md\`](three-way-cost.md). Nothing above licenses a claim
  that ADP is faster or slower than anything.
- **The retry loop has no backoff and no jitter**, and all writers start in the
  same millisecond. Real orchestrators would stagger. That makes the quadratic
  above an *upper bound* on contention cost, not a prediction of production
  behaviour — a deliberately adversarial arrangement, chosen because the
  optimistic one proves nothing.
- **Latency here is dominated by REST round-trips per attempt** (tree, commit,
  ref, proposal, merge — five calls), not by git object work. Read the latency
  column as "cost of a retry in this harness", not as "cost of a merge".
- **Single box, single Postgres, dev hardware.** Absolute throughput is not a
  capacity claim. The *shape* of the curve is the finding; the constants are not.

## What consumes this

Per the M2 readiness review, conflict-rate telemetry is a required input to two
open questions, not an optional extra:

- **A17 (contention avoided upstream).** If real orchestrators partition work so
  that ref-level contention is rare, this curve never gets exercised and the
  bottleneck lands elsewhere. The numbers here describe the cost *if* contention
  happens, which is what makes A17 an empirical question rather than a
  preference.
- **The M5 speculative-merge-batching gate**, which requires written
  justification citing M3/M4 telemetry. The quadratic attempt count is the
  argument such a justification would have to make — and it is now measurable
  rather than asserted. It is not on its own sufficient: A17 has to fail first.
`;
}

const METHOD_LABEL = {
  "github-gh": "GitHub + `gh`",
  "adp-gh": "ADP via `gh` (compat plane)",
  "adp-mcp": "ADP-MCP (native plane)",
};

function threeWayCostReport(records) {
  if (records.length === 0) {
    return "# Three-way cost comparison — arm 2 results\n\n**Not run.** No records in `bench/runs/` for this arm.\n";
  }

  const byMethod = new Map();
  for (const r of records) {
    const list = byMethod.get(r.method) ?? [];
    list.push(r);
    byMethod.set(r.method, list);
  }

  const tokensIn = (m) => m.usage.input_tokens + (m.usage.cache_creation_input_tokens ?? 0) + (m.usage.cache_read_input_tokens ?? 0);

  const rows = [...byMethod.entries()].map(([method, list]) => {
    const n = list.length;
    const landed = list.filter((r) => r.measurement.landed).length;
    const cost = list.reduce((s, r) => s + (r.measurement.totalCostUsd ?? 0), 0);
    const tIn = list.reduce((s, r) => s + tokensIn(r.measurement), 0);
    const tOut = list.reduce((s, r) => s + r.measurement.usage.output_tokens, 0);
    const calls = list.reduce((s, r) => s + r.measurement.toolCalls, 0);
    const errs = list.reduce((s, r) => s + r.measurement.toolErrors, 0);
    const wall = list.reduce((s, r) => s + r.measurement.wallClockMs, 0);
    return (
      `| ${METHOD_LABEL[method] ?? method} | ${n} | ${landed}/${n} | $${fmt(cost, 4)} | $${fmt(cost / n, 4)} | ` +
      `${fmt(tIn / n, 0)} | ${fmt(tOut / n, 0)} | ${fmt(calls / n, 1)} | ${fmt(errs / n, 2)} | ${fmt(wall / n / 1000, 1)}s |`
    );
  });

  const environments = [...new Set(records.map((r) => `${r.environment.platform}, node ${r.environment.node}`))];
  const models = [...new Set(records.map((r) => r.environment.model))];
  const tasks = [...new Set(records.map((r) => r.taskId))];
  const totalCost = records.reduce((s, r) => s + (r.measurement.totalCostUsd ?? 0), 0);
  const totalLanded = records.filter((r) => r.measurement.landed).length;

  const runIds = records
    .map((r) => `\`${r.method}/${r.taskId}/r${r.rep}\` → \`${r.environment.target.owner}/${r.environment.target.repo}\` (run \`${r.runId}\`)`)
    .join("\n- ");

  return `# Three-way cost comparison — arm 2 results

*Generated by \`bench/report/build-report.mjs\` from the run records in
[\`bench/runs/\`](../runs). Do not edit by hand: re-run the script.*

**Agent-backed. Stochastic — the spread matters, not a single figure.** The same
task suite (\`${tasks.join("`, `")}\`) completed by a real agent (the \`claude\` CLI,
non-interactively, \`--allowedTools\`-scoped per method) via three interfaces:
**GitHub + \`gh\`** against a real GitHub repository, **ADP via \`gh\`** (the
compat plane, unmodified \`gh\` pointed at ADP through \`GH_HOST\` — the MVP's own
success criterion), and **ADP-MCP** (the native plane: ADP's own MCP tool
surface, \`server/src/mcp/server.ts\`, plus \`git\` for plumbing and one \`curl\` call
for the one REST step the native MCP tools don't wrap — opening the proposal
itself; noted below, not hidden). Every trial's raw agent transcript
(token usage, tool calls, tool errors, permission denials) and landed-or-not
verdict is captured alongside its run record.

Environment: ${environments.join("; ")}. Model(s): ${models.join(", ")}.

**Pilot scale — this is not Study A.** ${records.length} trials across ${byMethod.size}
methods and ${tasks.length} tasks, reported per the M3-5 pilot-slice instruction to
run a small slice first, check actual cost-per-trial against budget, and only then
scale. It is enough to compare the three interfaces on
their own overhead; it is not enough reps per cell for a confidence interval,
and the numbers below are pilot-scale means, not statistically gated results.

| Method | n | Landed | Total cost | Avg cost/trial | Avg tokens in | Avg tokens out | Avg tool calls | Avg tool errors | Avg wall clock |
|---|---|---|---|---|---|---|---|---|---|
${rows.join("\n")}

**${totalLanded}/${records.length} trials landed.** Total spend: $${fmt(totalCost, 4)}.

## What this shows

**The compat plane (\`adp-gh\`) costs about the same as real GitHub.** Once the one-time
plumbing fixes were in (matching the git remote's host to \`GH_HOST\`, and this
instance's \`one_approval\` land policy — a real, deliberate constraint, not a bug —
requiring \`gh pr review --approve\` before \`gh pr merge\`), \`adp-gh\`'s per-trial cost,
tool-call count, and wall clock land close to \`github-gh\`'s. That is the MVP's own
success criterion showing up as a number: an unmodified \`gh\` workflow does not pay a
meaningfully higher agent-cost tax against ADP than against GitHub itself.

**The native plane (\`adp-mcp\`) costs more, and the reason is legible, not mysterious.**
Every \`adp-mcp\` trial needed the same \`git\` plumbing as the other two arms *plus* an
MCP round trip to open the candidate set, a \`curl\` call to open the proposal (the one
gap noted above), a second \`curl\` call to submit the required approving review, and an
MCP round trip to resolve — four extra tool calls with no \`gh\`-equivalent single
command standing in for any of them. That gap is a property of the native MCP tool
surface as it stood when these trials ran (no proposal-open tool), not of the native
plane's design in general.

**The gap is closed in the code, and these numbers predate the fix (#144).** The
native plane now has \`adp_intent_get\`, \`adp_proposal_open\`, \`adp_proposal_review\`
and \`adp_proposal_merge\`, and \`bench/arms/three-way-cost.mjs\` no longer allows
\`curl\` in the \`adp-mcp\` arm at all. **The arm has not been re-run since**, so
everything above still describes the pre-fix tool surface — which is the accurate
thing for it to describe, because these are the trials that produced the numbers.
Per this harness's own contract, an arm that was not run is reported as not run
rather than quietly restated: whether the fix moves the \`adp-mcp\` figure is an open
question until the re-run happens, and it will be published whichever way it points.

## What this does not show, and should not be read as showing

- **Pilot scale.** ${records.length} trials is enough to see the shape above, not enough to
  bound it with a confidence interval. Study-A-scale replication (more reps, more
  tasks, varied difficulty) is future work, not this report.
- **One model, fast tier, two small tasks.** Both tasks are solvable in a single
  agent pass by a competent model; neither exercises retries, multi-file changes,
  or a contested land. The interfaces may separate differently under harder work.
- **The native-plane MCP gap is closeable.** Nothing here says ADP's native plane
  is inherently costlier — it says today's \`~8\`-tool MCP surface has no
  proposal-open tool, so an agent using it pays for
  a REST round trip \`gh\` bundles into one command. That is an M3-5 finding for the
  native-plane MCP surface's own future scope, not a verdict on the plane itself.
- **Local dev server, not production infrastructure.** Same caveat as arm 1: single
  box, single Postgres. Absolute wall-clock numbers are not a capacity claim.
- **The approvals in these trials were self-approvals** (noted 2026-08-29). Each arm
  ran as a single principal, so \`gh pr review --approve\` and \`gh pr merge\` were the
  same agent — which \`one_approval\` accepted at the time, and no longer does (#121,
  now author-independent). The numbers above are unaffected: the approving call was
  made and paid for either way, and re-running these arms today would cost the same
  tool call from a second token. What it does mean is that this run measured the cost
  of the requirement, never its effect.

## Run ids

Every trial's ADP-hosted target and run id, so a reader can look up the underlying
evidence without re-running an agent:

- ${runIds}

## What consumes this

Per the M3-5 spec, this arm's own reason to exist is
the same three interfaces measured on the same work — a number the fork's own
benchmark-gates-investment stance (A1) says gets published whichever way it points.
It is also the first first-party evidence for whether the native plane's promised
value (undo, evidence bundles, workspaces, candidate sets — what GitHub has no
analogue for) comes at a measurable agent-cost premium over the compat plane for
ordinary single-agent work, distinct from the cases (fan-out, cross-harness resume)
where the native plane's *capabilities* are the point rather than its cost.
`;
}

async function main() {
  const mergeRecords = await loadRuns("merge-contention");
  const mergeTarget = path.join(here, "merge-contention.md");
  await writeFile(mergeTarget, mergeContentionReport(mergeRecords));
  console.error(`wrote ${path.relative(process.cwd(), mergeTarget)} from ${mergeRecords.length} run record(s)`);

  const costRecords = await loadRuns("three-way-cost");
  const costTarget = path.join(here, "three-way-cost.md");
  await writeFile(costTarget, threeWayCostReport(costRecords));
  console.error(`wrote ${path.relative(process.cwd(), costTarget)} from ${costRecords.length} run record(s)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
