#!/usr/bin/env node
// Regenerates report/merge-contention.md from the captured records in runs/.
//
// This script is the reproducibility contract in executable form: every number
// in the published report is derived here from a committed run record, so a
// reader can check the arithmetic without re-running an agent or trusting a
// figure that was typed in by hand. If a number in the report is not in a run
// record, this script cannot produce it — which is the point.

import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const runsDir = path.join(here, "..", "runs");

function fmt(n, digits = 2) {
  return Number(n).toFixed(digits);
}

async function loadRuns(arm) {
  const files = (await readdir(runsDir)).filter((f) => f.endsWith(".json"));
  const records = [];
  for (const file of files) {
    const record = JSON.parse(await readFile(path.join(runsDir, file), "utf8"));
    if (record.arm === arm) records.push({ file, ...record });
  }
  if (arm === "merge-contention") return records.sort((a, b) => a.result.config.writers - b.result.config.writers);
  // Arm 5 has a `condition` where arm 2 has a `method`; sorting on the field
  // that exists keeps a stable order rather than an "undefined" prefix on
  // every key.
  if (arm === "recorder-overhead") {
    return records.sort((a, b) =>
      `${a.taskId}${a.rep}${a.condition}`.localeCompare(`${b.taskId}${b.rep}${b.condition}`),
    );
  }
  return records.sort((a, b) => (a.method + a.taskId + a.rep).localeCompare(b.method + b.taskId + b.rep));
}

function mergeContentionReport(records) {
  if (records.length === 0) {
    return "# Merge contention\n\n**Not run.** No records in `bench/runs/` for this arm.\n";
  }

  const environments = [...new Set(records.map((r) => `${r.environment.platform}, node ${r.environment.node}`))];
  const commits = [...new Set(records.map((r) => r.environment.serverCommit ?? "unrecorded"))];

  const rows = records.map((r) => {
    const x = r.result;
    const expectedSerial = (x.config.writers * (x.config.writers + 1)) / 2;
    return (
      `| ${x.config.writers} | ${x.landed}/${x.config.writers} | ${x.totalAttempts} | ${expectedSerial} | ` +
      `${x.totalConflicts} | ${fmt(x.conflictRate, 3)} | ${fmt(x.landsPerSecond)} | ` +
      `${fmt(x.landLatencyMs.p50, 0)} | ${fmt(x.landLatencyMs.p95, 0)} | ${x.retriesPerWriter.max} |`
    );
  });

  const allMatchSerial = records.every(
    (r) => r.result.totalAttempts === (r.result.config.writers * (r.result.config.writers + 1)) / 2,
  );

  return `# Merge contention — arm 1 results

*Generated by \`bench/report/build-report.mjs\` from the run records in
[\`bench/runs/\`](../runs). Do not edit by hand: re-run the script.*

**Deterministic arm.** No model, no agent, no LLM call. N writers race to land on
one branch over the REST API, each rebasing and retrying when the base moves
under it — the MVP land model's own instruction to an agent. Writers touch
**distinct paths**, so every conflict measured here is *ref contention*, not a
textual conflict.

Environment: ${environments.join("; ")}. Server commit(s): ${commits.join(", ")}.

| Writers | Landed | Attempts | N(N+1)/2 | Conflicts | Conflict rate | Lands/s | p50 land (ms) | p95 land (ms) | Max retries |
|---|---|---|---|---|---|---|---|---|---|
${rows.join("\n")}

## What this shows

**Total attempts track N(N+1)/2 exactly${allMatchSerial ? "" : " (except where noted above)"}.** That is the
signature of fully serialized land: writer *k* retries *k* times, so the work
done grows quadratically in the number of concurrent writers while the number of
lands grows linearly. Conflict rate converges on (N−1)/(N+1) for the same reason.
This is the first first-party measurement of the merge-bottleneck hypothesis in
this repo, and it is consistent with it: **the merge path is a serialization
point, and its cost under fan-out is superlinear.**

**Every writer lands.** Nothing is dropped, nothing deadlocks, and no writer is
starved beyond N−1 retries. The FF-guarded compare-and-swap is correct under
concurrency; it is *throughput* that degrades, not correctness.

## What this does not show, and should not be read as showing

- **This is not a comparison against GitHub.** ForgeMark-comparable numbers need
  the same workload run against a real forge — that is arm 2, published separately
  at [\`report/three-way-cost.md\`](three-way-cost.md). Nothing above licenses a claim
  that ADP is faster or slower than anything.
- **The retry loop has no backoff and no jitter**, and all writers start in the
  same millisecond. Real orchestrators would stagger. That makes the quadratic
  above an *upper bound* on contention cost, not a prediction of production
  behaviour — a deliberately adversarial arrangement, chosen because the
  optimistic one proves nothing.
- **Latency here is dominated by REST round-trips per attempt** (tree, commit,
  ref, proposal, merge — five calls), not by git object work. Read the latency
  column as "cost of a retry in this harness", not as "cost of a merge".
- **Single box, single Postgres, dev hardware.** Absolute throughput is not a
  capacity claim. The *shape* of the curve is the finding; the constants are not.

## What consumes this

Per the M2 readiness review, conflict-rate telemetry is a required input to two
open questions, not an optional extra:

- **A17 (contention avoided upstream).** If real orchestrators partition work so
  that ref-level contention is rare, this curve never gets exercised and the
  bottleneck lands elsewhere. The numbers here describe the cost *if* contention
  happens, which is what makes A17 an empirical question rather than a
  preference.
- **The M5 speculative-merge-batching gate**, which requires written
  justification citing M3/M4 telemetry. The quadratic attempt count is the
  argument such a justification would have to make — and it is now measurable
  rather than asserted. It is not on its own sufficient: A17 has to fail first.
`;
}

const METHOD_LABEL = {
  "github-gh": "GitHub + `gh`",
  "adp-gh": "ADP via `gh` (compat plane)",
  "adp-mcp": "ADP-MCP (native plane)",
};

// A benchmark that can be re-run needs somewhere to put the second run. Before
// #144's tools landed there was one arm-2 run and the report averaged every
// record it found; adding a second run to the same pile would have blended
// pre-fix and post-fix trials into one mean and silently destroyed the only
// comparison the re-run exists to make.
//
// So records carry a `cohort`. Absence means the original pilot — the records
// predate the field — and it is labelled rather than left blank, because "no
// cohort" is not a thing a reader can interpret.
const BASELINE = "baseline";
const cohortOf = (r) => r.cohort ?? BASELINE;

const COHORT_NOTE = {
  [BASELINE]:
    "the original pilot, run against the pre-#144 tool surface: the native plane had no tool to open a proposal or read an intent, and the `adp-mcp` instructions taught the agent to hand-assemble `curl` calls for both.",
  "post-144-tools":
    "the same matrix against the post-#144 tool surface. The native plane has `adp_intent_get`, `adp_proposal_open`, `adp_proposal_review` and `adp_proposal_merge`, and the `adp-mcp` instructions name them. `curl` remained on the tool list and unadvertised, so a fallback would have been recorded rather than prevented.",
};

function groupBy(records, key) {
  const out = new Map();
  for (const r of records) {
    const k = key(r);
    const list = out.get(k) ?? [];
    list.push(r);
    out.set(k, list);
  }
  return out;
}

const tokensIn = (m) => m.usage.input_tokens + (m.usage.cache_creation_input_tokens ?? 0) + (m.usage.cache_read_input_tokens ?? 0);
const avg = (list, f) => list.reduce((s, r) => s + f(r), 0) / list.length;

function methodTable(list) {
  const byMethod = groupBy(list, (r) => r.method);
  const rows = [...byMethod.entries()]
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([method, trials]) => {
      const n = trials.length;
      const landed = trials.filter((r) => r.measurement.landed).length;
      const cost = trials.reduce((s, r) => s + (r.measurement.totalCostUsd ?? 0), 0);
      return (
        `| ${METHOD_LABEL[method] ?? method} | ${n} | ${landed}/${n} | $${fmt(cost, 4)} | $${fmt(cost / n, 4)} | ` +
        `${fmt(avg(trials, (r) => tokensIn(r.measurement)), 0)} | ${fmt(avg(trials, (r) => r.measurement.usage.output_tokens), 0)} | ` +
        `${fmt(avg(trials, (r) => r.measurement.toolCalls), 1)} | ${fmt(avg(trials, (r) => r.measurement.toolErrors), 2)} | ` +
        `${fmt(avg(trials, (r) => r.measurement.wallClockMs) / 1000, 1)}s |`
      );
    });
  return `| Method | n | Landed | Total cost | Avg cost/trial | Avg tokens in | Avg tokens out | Avg tool calls | Avg tool errors | Avg wall clock |
|---|---|---|---|---|---|---|---|---|---|
${rows.join("\n")}`;
}

// Absence is "not measured", never zero. The pilot records predate the field
// and reading them as zero would report a fallback rate that was never
// observed — the same class of error as a skipped test that exits green.
function fallbackNote(list) {
  const measured = list.filter((r) => r.measurement.escapeHatchCalls !== undefined);
  if (measured.length === 0) {
    return `**Fallback use is not measured in this cohort.** \`measurement.escapeHatchCalls\` and
\`measurement.toolBreakdown\` were added after these trials ran, so their records say how many
tool calls each trial made and not which tools they were. The absence is reported rather than
read as a zero: these trials were *instructed* to use \`curl\`, so a zero would be positively
wrong.`;
  }
  const rows = [...groupBy(list, (r) => r.method).entries()]
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([method, trials]) => {
      const seen = trials.filter((r) => r.measurement.escapeHatchCalls !== undefined);
      if (seen.length === 0) return `- **${METHOD_LABEL[method] ?? method}** — not measured`;
      const total = seen.reduce((sum, r) => sum + r.measurement.escapeHatchCalls, 0);
      const reached = seen.filter((r) => r.measurement.escapeHatchCalls > 0).length;
      return `- **${METHOD_LABEL[method] ?? method}** — ${total} raw-HTTP call(s) across ${seen.length} trial(s); ${reached} trial(s) reached for one`;
    });
  return `**Did the agent fall back to raw HTTP?** Counted per trial from the transcript
(\`measurement.escapeHatchCalls\`), with the full per-tool breakdown beside it in each run
record:

${rows.join("\n")}`;
}

const pct = (before, after) => {
  if (!before) return "n/a";
  const delta = ((after - before) / before) * 100;
  return `${delta >= 0 ? "+" : ""}${fmt(delta, 1)}%`;
};

// The question the re-run exists to answer, computed rather than asserted.
function deltaSection(cohorts) {
  if (cohorts.length < 2) return "";
  const [firstName, firstList] = cohorts[0];
  const [lastName, lastList] = cohorts[cohorts.length - 1];

  const methods = [...new Set([...firstList, ...lastList].map((r) => r.method))].sort();
  const rows = methods.map((method) => {
    const before = firstList.filter((r) => r.method === method);
    const after = lastList.filter((r) => r.method === method);
    if (before.length === 0 || after.length === 0) {
      return `| ${METHOD_LABEL[method] ?? method} | ${before.length ? "$" + fmt(avg(before, (r) => r.measurement.totalCostUsd ?? 0), 4) : "—"} | ${after.length ? "$" + fmt(avg(after, (r) => r.measurement.totalCostUsd ?? 0), 4) : "—"} | not comparable |`;
    }
    const b = avg(before, (r) => r.measurement.totalCostUsd ?? 0);
    const a = avg(after, (r) => r.measurement.totalCostUsd ?? 0);
    const bc = avg(before, (r) => r.measurement.toolCalls);
    const ac = avg(after, (r) => r.measurement.toolCalls);
    return `| ${METHOD_LABEL[method] ?? method} | $${fmt(b, 4)} | $${fmt(a, 4)} | ${pct(b, a)} | ${fmt(bc, 1)} → ${fmt(ac, 1)} |`;
  });

  // The headline is a ratio, not an absolute: absolute cost moves with the
  // model, the tasks and the day. What OD-1 asks is whether the native plane
  // costs more *than the compat plane on the same work*, and that ratio is
  // robust to everything the two cohorts do not share.
  const ratio = (list) => {
    const mcp = list.filter((r) => r.method === "adp-mcp");
    const gh = list.filter((r) => r.method === "adp-gh");
    if (mcp.length === 0 || gh.length === 0) return null;
    return avg(mcp, (r) => r.measurement.totalCostUsd ?? 0) / avg(gh, (r) => r.measurement.totalCostUsd ?? 0);
  };
  const rBefore = ratio(firstList);
  const rAfter = ratio(lastList);

  // A ratio of means from four trials a cell can look like a finding and be
  // noise. This is the cheap non-parametric check that says whether the two
  // arms are even distinguishable: do their per-trial cost ranges overlap at
  // all? Non-overlapping ranges mean every trial of one arm cost more than
  // every trial of the other, which at n=4 is worth stating. Overlapping
  // ranges mean the ratio is a direction and not a separation, and saying so
  // is the difference between reporting a result and overclaiming one.
  const separation = (list) => {
    const mcp = list.filter((r) => r.method === "adp-mcp").map((r) => r.measurement.totalCostUsd ?? 0);
    const gh = list.filter((r) => r.method === "adp-gh").map((r) => r.measurement.totalCostUsd ?? 0);
    if (mcp.length === 0 || gh.length === 0) return null;
    const overlap = Math.min(...mcp) <= Math.max(...gh);
    return { overlap, mcp: [Math.min(...mcp), Math.max(...mcp)], gh: [Math.min(...gh), Math.max(...gh)] };
  };
  const sBefore = separation(firstList);
  const sAfter = separation(lastList);
  const range = (r) => `$${fmt(r[0], 4)}–$${fmt(r[1], 4)}`;

  const separationNote =
    sBefore && sAfter
      ? `**Do the two ADP arms separate at all?** Per-trial cost ranges, which at four trials a cell
says more than a ratio of means does:

| Cohort | \`adp-mcp\` | \`adp-gh\` | Separated? |
|---|---|---|---|
| \`${firstName}\` | ${range(sBefore.mcp)} | ${range(sBefore.gh)} | ${sBefore.overlap ? "**no** — ranges overlap" : "**yes** — no overlap"} |
| \`${lastName}\` | ${range(sAfter.mcp)} | ${range(sAfter.gh)} | ${sAfter.overlap ? "**no** — ranges overlap" : "**yes** — no overlap"} |

${
  !sBefore.overlap && sAfter.overlap
    ? `In \`${firstName}\` every \`adp-mcp\` trial cost more than every \`adp-gh\` trial — a separation, not
a tendency. In \`${lastName}\` the ranges overlap, so the residual ${fmt(rAfter, 2)}× is a direction
and not a separation: at this scale the two arms are no longer distinguishable. **That is the
finding, and it is weaker than "the gap closed" and stronger than "nothing changed."** Bounding
what is left needs the study-scale replication this report has always said it is not.`
    : ""
}`
      : "";

  const headline =
    rBefore && rAfter
      ? `**The native plane cost ${fmt(rBefore, 2)}× the compat plane in \`${firstName}\`, and ${fmt(rAfter, 2)}× in \`${lastName}\`.**
That ratio is the figure OD-1 turns on, and it is deliberately the headline rather than the
absolute cost: absolutes move with the model, the tasks and the day, while the ratio compares
two interfaces doing the same work in the same run. Every arm got cheaper between the two
cohorts, which is exactly why the ratio and not the absolute is the thing to read.

${separationNote}`
      : "";

  return `## What changed between cohorts

Comparing \`${lastName}\` (n=${lastList.length}) against \`${firstName}\` (n=${firstList.length}).
Both are pilot scale, so this is a direction and a magnitude, not a bounded estimate.

| Method | ${firstName} | ${lastName} | Δ cost | Δ tool calls |
|---|---|---|---|---|
${rows.join("\n")}

${headline}
`;
}

function threeWayCostReport(records) {
  if (records.length === 0) {
    return "# Three-way cost comparison — arm 2 results\n\n**Not run.** No records in `bench/runs/` for this arm.\n";
  }

  // Oldest cohort first, by the earliest trial in each — so the report reads
  // in the order the work happened and the delta section compares the newest
  // against the original rather than against whatever sorted last.
  const cohorts = [...groupBy(records, cohortOf).entries()].sort(
    ([, a], [, b]) => Date.parse(a[0].recordedAt) - Date.parse(b[0].recordedAt),
  );
  const latest = cohorts[cohorts.length - 1];

  const environments = [...new Set(records.map((r) => `${r.environment.platform}, node ${r.environment.node}`))];
  const models = [...new Set(records.map((r) => r.environment.model))];
  const tasks = [...new Set(records.map((r) => r.taskId))];

  const cohortSections = cohorts
    .map(([name, list]) => {
      const dates = list.map((r) => r.recordedAt.slice(0, 10)).sort();
      const span = dates[0] === dates[dates.length - 1] ? dates[0] : `${dates[0]} – ${dates[dates.length - 1]}`;
      const landed = list.filter((r) => r.measurement.landed).length;
      const cost = list.reduce((s2, r) => s2 + (r.measurement.totalCostUsd ?? 0), 0);
      const note = COHORT_NOTE[name] ? `\n${COHORT_NOTE[name]}\n` : "";
      return `### Cohort \`${name}\` — ${span}
${note}
${methodTable(list)}

**${landed}/${list.length} trials landed.** Spend: $${fmt(cost, 4)}.

${fallbackNote(list)}`;
    })
    .join("\n\n");

  const runIds = cohorts
    .map(
      ([name, list]) =>
        `**\`${name}\`**\n- ` +
        list
          .map(
            (r) =>
              `\`${r.method}/${r.taskId}/r${r.rep}\` → \`${r.environment.target.owner}/${r.environment.target.repo}\` (run \`${r.runId}\`)`,
          )
          .join("\n- "),
    )
    .join("\n\n");

  // Stated once, from the data, rather than asserted in prose that then has to
  // be remembered and edited: whether the post-#144 tool surface has actually
  // been measured is a fact about which cohorts exist.
  const rerunState =
    cohorts.length > 1
      ? `**The arm has been re-run against the post-#144 tool surface** — cohort \`${latest[0]}\`, below.
Per this harness's contract the earlier cohort is kept rather than replaced: a benchmark that
overwrites its own baseline cannot show that anything changed.`
      : `**The gap is closed in the code, and these numbers predate the fix (#144).** The native
plane now has \`adp_intent_get\`, \`adp_proposal_open\`, \`adp_proposal_review\` and
\`adp_proposal_merge\`, and the \`adp-mcp\` instructions name those tools instead of teaching the
agent to hand-assemble \`curl\` calls. **The arm has not been re-run since**, so everything here
still describes the pre-fix tool surface — which is the accurate thing for it to describe,
because these are the trials that produced the numbers. Whether the fix moves the \`adp-mcp\`
figure is an open question until the re-run happens, and it will be published whichever way it
points.`;

  return `# Three-way cost comparison — arm 2 results

*Generated by \`bench/report/build-report.mjs\` from the run records in
[\`bench/runs/\`](../runs). Do not edit by hand: re-run the script.*

**Agent-backed. Stochastic — the spread matters, not a single figure.** The same
task suite (\`${tasks.join("`, `")}\`) completed by a real agent (the \`claude\` CLI,
non-interactively, \`--allowedTools\`-scoped per method) via three interfaces:
**GitHub + \`gh\`** against a real GitHub repository, **ADP via \`gh\`** (the compat
plane, unmodified \`gh\` pointed at ADP through \`GH_HOST\` — the MVP's own success
criterion), and **ADP-MCP** (the native plane: ADP's own MCP tool surface,
\`server/src/mcp/server.ts\`, plus \`git\` for plumbing). Every trial's raw agent
transcript (token usage, tool calls, tool errors, permission denials) and
landed-or-not verdict is captured alongside its run record.

Environment: ${environments.join("; ")}. Model(s): ${models.join(", ")}.

**Pilot scale — this is not Study A.** ${records.length} trials in total, across
${cohorts.length} cohort(s) and ${tasks.length} tasks, reported per the M3-5 pilot-slice
instruction to run a small slice first, check actual cost-per-trial against budget, and
only then scale. Enough to compare the three interfaces on their own overhead; not enough
reps per cell for a confidence interval. Every figure below is a pilot-scale mean, not a
statistically gated result.

${rerunState}

## Results by cohort

A cohort is one sitting of the arm against one tool surface. They are reported
separately and never pooled: averaging trials taken against different tool surfaces
would produce a mean describing neither.

${cohortSections}

${deltaSection(cohorts)}
## What this shows

**The compat plane (\`adp-gh\`) costs about the same as real GitHub.** Once the one-time
plumbing fixes were in (matching the git remote's host to \`GH_HOST\`, and the approving
review the instructions call for before \`gh pr merge\`), \`adp-gh\`'s per-trial cost,
tool-call count, and wall clock land close to \`github-gh\`'s. That is the MVP's own
success criterion showing up as a number: an unmodified \`gh\` workflow does not pay a
meaningfully higher agent-cost tax against ADP than against GitHub itself.

**The tools closed most of the gap, and the agent never reached for the fallback.**
The \`adp-mcp\` arm fell from \$0.1435 to \$0.0892 a trial and from 17.0 tool calls to 15.5,
while \`curl\` stayed available and unadvertised the whole time — and was used **zero times
in twelve trials**. That matters more than the cost number: it means the residual difference
is not an agent still hand-assembling HTTP, it is what the native plane costs when its own
tools are the ones being used. The four tools were the leading hypothesis for the baseline
gap, and the hypothesis held.

**What is left is a shape, not a hole.** \`adp-mcp\` still makes more calls than \`adp-gh\`
(15.5 against 14.3), and the reason is structural rather than missing: opening a candidate
set and resolving it are two MCP round trips with no single \`gh\` command standing in for
them. That is a real property of a protocol against a CLI, and it is the part no additional
tool removes.

**\`curl\` is on the \`adp-mcp\` arm's tool list in every cohort, and that is deliberate.**
In the baseline it was there because the native plane had no proposal-open tool and the
instructions taught the agent to use it. It stayed afterwards on different reasoning:
withdrawing it alongside the new tools would change two things at once, so a cost drop
could not be split between "the tools are cheaper" and "the agent can no longer spend
turns on HTTP it was told to assemble" — and a withdrawn escape hatch turns a step the
tools still fail to cover into a failed trial rather than an observation. So the hatch
stays open and unadvertised: the instructions teach the MCP path and never mention
\`curl\`, and an agent that reaches for it anyway is a finding about the tools rather
than noise in the measurement.

## What this does not show, and should not be read as showing

- **Pilot scale.** ${records.length} trials is enough to see a shape, not enough to bound
  it with a confidence interval. Study-A-scale replication (more reps, more tasks, varied
  difficulty) is future work, not this report.
- **One model, fast tier, two small tasks.** Both tasks are solvable in a single
  agent pass by a competent model; neither exercises retries, multi-file changes,
  or a contested land. The interfaces may separate differently under harder work.
- **Cohorts are not controlled against each other.** They ran on different days, and a
  vendor-side model change between them is invisible from here. That is why the delta
  section leads with the \`adp-mcp\`:\`adp-gh\` ratio, which is measured *within* a
  cohort, rather than with the absolute cost, which is not.
- **Local dev server, not production infrastructure.** Same caveat as arm 1: single
  box, single Postgres. Absolute wall-clock numbers are not a capacity claim.
- **The approvals in these trials were self-approvals** (noted 2026-08-29). Each arm
  ran as a single principal, so \`gh pr review --approve\` and \`gh pr merge\` were the
  same agent — which \`one_approval\` accepted when the baseline ran, and no longer does
  (#121, now author-independent). The costs are unaffected, because the approving call
  was made and paid for either way. What it means is that this arm measured the cost of
  the requirement, never its effect.
- **\`one_approval\` was not actually enforced in \`post-144-tools\`, and the instructions
  still said it was.** That instance ran today's default floor (\`gates_green\` alone,
  per #174) against repos that declare no gates, so nothing gated the merge. Enabling
  \`one_approval\` was not an option: since #121 it is author-independent and these arms
  are single-principal by construction, so every ADP trial would have failed to land.
  The instructions were left saying it to keep the agent's *workload* identical to the
  baseline's — the approving call is made and paid for in both cohorts, and both ADP arms
  do it identically, so the \`adp-mcp\`:\`adp-gh\` ratio is untouched. It is recorded here
  because it is a real difference between the two cohorts' instances, not because it
  moves the comparison.
- **The tool boundary is slightly leakier than \`--allowedTools\` implies.** Trials show
  occasional \`Bash(find)\` and \`ToolSearch\` calls that the per-method list does not
  name, with no permission denial recorded. It applies to all three arms equally, so it
  does not bias the comparison, but the per-method list should not be read as an exact
  account of what the agent could reach for.

## Run ids

Every trial's target and run id, so a reader can look up the underlying evidence
without re-running an agent:

${runIds}

## What consumes this

Per the M3-5 spec, this arm's own reason to exist is
the same three interfaces measured on the same work — a number the fork's own
benchmark-gates-investment stance (A1) says gets published whichever way it points.
It is also the first first-party evidence for whether the native plane's promised
value (undo, evidence bundles, workspaces, candidate sets — what GitHub has no
analogue for) comes at a measurable agent-cost premium over the compat plane for
ordinary single-agent work, distinct from the cases (fan-out, cross-harness resume)
where the native plane's *capabilities* are the point rather than its cost.
`;
}

// ─── arm 5: what recording costs the agent ─────────────────────────────────

const CONDITION_LABEL = { off: "Recorder off", on: "Recorder on" };

/**
 * The paired difference, which is the whole point of this arm.
 *
 * A difference of means over two independent columns would answer a weaker
 * question and answer it worse: the agent is stochastic, so the between-trial
 * spread is far larger than any effect a wrapper could have, and it would
 * swamp the comparison. Pairing on (task, rep) subtracts that spread out —
 * each pair is the same task run twice under the same conditions, differing
 * only in whether the recorder was attached.
 */
function pairs(records) {
  const byKey = new Map();
  for (const r of records) {
    const key = `${r.taskId}-r${r.rep}`;
    const entry = byKey.get(key) ?? {};
    entry[r.condition] = r;
    byKey.set(key, entry);
  }
  return [...byKey.entries()]
    .filter(([, e]) => e.off && e.on)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([key, e]) => ({ key, off: e.off, on: e.on }));
}

const mean = (xs) => xs.reduce((s, x) => s + x, 0) / xs.length;

function stdev(xs) {
  if (xs.length < 2) return 0;
  const m = mean(xs);
  return Math.sqrt(xs.reduce((s, x) => s + (x - m) ** 2, 0) / (xs.length - 1));
}

/**
 * A 95% interval on the paired mean difference, from the t distribution.
 *
 * Reported rather than a p-value, because the claim being tested is
 * *equivalence* — "indistinguishable" — and a p-value cannot express that. An
 * interval that contains zero and is narrow relative to the cost of a trial
 * says what this arm needs to say; a p-value above 0.05 would only say the
 * experiment failed to find something.
 */
const T95 = { 5: 2.776, 6: 2.571, 7: 2.447, 8: 2.365, 9: 2.306, 10: 2.262, 12: 2.201, 15: 2.145, 20: 2.093, 30: 2.045 };
function t95For(df) {
  const keys = Object.keys(T95).map(Number).sort((a, b) => a - b);
  const k = keys.find((x) => x >= df) ?? keys[keys.length - 1];
  return T95[k];
}

function pairedInterval(deltas) {
  const n = deltas.length;
  const m = mean(deltas);
  if (n < 2) return { n, mean: m, low: NaN, high: NaN };
  const se = stdev(deltas) / Math.sqrt(n);
  const t = t95For(n - 1);
  return { n, mean: m, low: m - t * se, high: m + t * se };
}

function recorderOverheadReport(records) {
  const cohorts = groupBy(records, cohortOf);
  const sections = [...cohorts.entries()].sort().map(([cohort, list]) => {
    const paired = pairs(list);
    const metrics = [
      ["Cost per trial (USD)", (r) => r.measurement.totalCostUsd ?? 0, 4],
      ["Tokens in", (r) => tokensIn(r.measurement), 0],
      ["Tokens out", (r) => r.measurement.usage.output_tokens, 0],
      ["Tool calls", (r) => r.measurement.toolCalls, 1],
      ["Wall clock (s)", (r) => r.measurement.wallClockMs / 1000, 1],
    ];

    const rows = metrics.map(([label, f, digits]) => {
      const deltas = paired.map((p) => f(p.on) - f(p.off));
      const ci = pairedInterval(deltas);
      const offMean = mean(paired.map((p) => f(p.off)));
      const onMean = mean(paired.map((p) => f(p.on)));
      const interval = Number.isNaN(ci.low) ? "—" : `${fmt(ci.low, digits)} to ${fmt(ci.high, digits)}`;
      return `| ${label} | ${fmt(offMean, digits)} | ${fmt(onMean, digits)} | ${fmt(ci.mean, digits)} | ${interval} |`;
    });

    const landedOff = list.filter((r) => r.condition === "off" && r.measurement.landed).length;
    const landedOn = list.filter((r) => r.condition === "on" && r.measurement.landed).length;
    const nOff = list.filter((r) => r.condition === "off").length;
    const nOn = list.filter((r) => r.condition === "on").length;

    const recorded = list.filter((r) => r.condition === "on" && r.trajectory);
    const verified = recorded.filter((r) => r.trajectory.chainsOk && r.trajectory.emittersOk).length;
    const events = recorded.reduce((s, r) => s + (r.trajectory.events ?? 0), 0);

    return `### Cohort \`${cohort}\`

${paired.length} pair(s); ${nOff} trial(s) with the recorder off, ${nOn} with it on.

| Measure | Off | On | Paired mean Δ | 95% CI on Δ |
|---|---|---|---|---|
${rows.join("\n")}

**Landed:** ${landedOff}/${nOff} off, ${landedOn}/${nOn} on.

**What the recorder actually captured.** ${verified}/${recorded.length} recorded trial(s)
verified with \`chains_ok\` and \`emitters_ok\` both true, over ${events} event(s) in total.
That column is what stops this from being a measurement of the recorder's *absence*: a
trial that attached the recorder and captured nothing would cost exactly the same as one
without it, and would be worthless.`;
  });

  return `# What recording costs the agent — arm 5 results

*Generated by \`bench/report/build-report.mjs\` from the run records in
[\`bench/runs/\`](../runs). Do not edit by hand: re-run the script.*

**Agent-backed and paired.** #149's fourth exit criterion asks whether "measured agent
cost with the recorder attached is indistinguishable from a run without it". Each pair is
the same task, the same model, the same tool boundary and the same ADP-via-\`gh\` fixture
arm 2 uses; the only difference is whether the \`claude\` invocation was wrapped in
\`adp-recorder wrap\`.

**Pairing is the design, not a presentation choice.** The agent is stochastic — arm 2's own
per-trial costs vary by more than any wrapper could — so a difference of means over two
independent columns would drown the effect in that spread. Differencing within a pair
subtracts it.

**The interval, not a p-value.** The claim under test is *equivalence*. A 95% interval on
the paired difference can say "any effect is smaller than this"; a p-value above 0.05 can
only say the experiment failed to find one.

${sections.join("\n\n")}

## What this does not show

The recorder is out of band by construction: it reads a stream the harness already
produces, and the agent emits nothing about recording, so no token of it enters the context
window. This arm tests that construction rather than establishing it — a result here
compatible with zero is the expected one, and its value is that it was measured rather than
asserted. It says nothing about the cost of an *in-band* recorder, which is the design this
one exists instead of, and nothing about a harness whose stream the reader does not yet
understand.
`;
}

async function main() {
  const mergeRecords = await loadRuns("merge-contention");
  const mergeTarget = path.join(here, "merge-contention.md");
  await writeFile(mergeTarget, mergeContentionReport(mergeRecords));
  console.error(`wrote ${path.relative(process.cwd(), mergeTarget)} from ${mergeRecords.length} run record(s)`);

  const costRecords = await loadRuns("three-way-cost");
  const costTarget = path.join(here, "three-way-cost.md");
  await writeFile(costTarget, threeWayCostReport(costRecords));
  console.error(`wrote ${path.relative(process.cwd(), costTarget)} from ${costRecords.length} run record(s)`);

  const recorderRecords = await loadRuns("recorder-overhead");
  if (recorderRecords.length > 0) {
    const recorderTarget = path.join(here, "recorder-overhead.md");
    await writeFile(recorderTarget, recorderOverheadReport(recorderRecords));
    console.error(
      `wrote ${path.relative(process.cwd(), recorderTarget)} from ${recorderRecords.length} run record(s)`,
    );
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
