// `adp connect <harness>` — one command, and then the harness records itself.
//
// **The problem this closes is a list of things nobody should have to know**
// (#154): mint a token by hand, write an MCP config in the right format at the
// right path, know that `gh` reads `GH_ENTERPRISE_TOKEN` rather than `GH_TOKEN`
// for a non-github.com host, install a hook that writes the trailer #142 reads,
// and then write the trajectory integration yourself because none shipped. Every
// one of those is knowledge a command should hold.
//
// **And then it proves it worked.** A config written to the wrong path fails
// silently and looks exactly like success, which is why the last thing connect
// does is open a session with the token it just minted and close it again. That
// round trip is the difference between a setup command and a setup command
// anyone trusts: it exercises the credential, the server URL, the repository
// resolution and the scope, and it fails loudly when any of them is wrong.
import { existsSync } from "node:fs";
import { chmodSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { spawn, spawnSync } from "node:child_process";
import path from "node:path";
import { parseFlags, splitRepo } from "../args.js";
import { loadConfig } from "../config.js";
import { apiRequest, ApiError } from "../api.js";
import { findHarness, harnessNames, removeMcpServer, writeMcpServer, type Harness } from "../harnesses.js";
import { excludePaths, hooksDir, installHook, removeHook, remoteRepo, repoRoot, unexcludePaths } from "../git.js";
import { CLAUDE_SETTINGS, removeSessionStartHook, writeSessionStartHook } from "../harnesses.js";
import { loadRepoIdentity, saveRepoIdentity } from "../repo-identity.js";
// #242: one answer to "where is the recorder", shared with `bakeoff --launch`.
import { installRoot, recorderBin } from "../recorder-bin.js";

interface MintedToken {
  token: string;
  scopes: string[];
}

/**
 * How to run ADP's MCP server, preferring the built artifact.
 *
 * `node dist/mcp/server.js` where a build exists, and the direct `tsx` binary
 * otherwise — **never `npx tsx`**, whose own resolution adds a cold start that
 * raced Claude Code's MCP connect timeout often enough in this repository's own
 * benchmark harness to be worth avoiding rather than tuning around. That is
 * exactly the kind of thing a command should hold and a user should never
 * acquire.
 */
function mcpCommand(root: string): { command: string; args: string[] } | null {
  const built = path.join(root, "server", "dist", "mcp", "server.js");
  if (existsSync(built)) return { command: process.execPath, args: [built] };
  const tsx = path.join(root, "server", "node_modules", ".bin", "tsx");
  const source = path.join(root, "server", "src", "mcp", "server.ts");
  if (existsSync(tsx) && existsSync(source)) return { command: tsx, args: [source] };
  return null;
}

/** Marker on every file connect generates whole, so disconnect removes only its own. */
const MARKER = "# generated by `adp connect` — remove with `adp disconnect`";

export async function connect(argv: string[]): Promise<void> {
  const [name, ...rest] = argv;
  const flags = parseFlags(rest);
  const harness = name ? findHarness(name) : null;
  if (!harness) {
    throw new Error(`usage: adp connect <${harnessNames().join("|")}> [--repo <owner>/<repo>] [--model <name>]`);
  }

  const config = await loadConfig();
  const root = repoRoot(process.cwd());
  if (!root) throw new Error("run this inside a git repository — connect writes its configuration into the repo");

  const target = resolveRepoTarget(root, config.serverUrl, flags.repo);

  const mcp = mcpCommand(installRoot());
  if (!mcp) {
    throw new Error(
      `cannot find ADP's MCP server under ${installRoot()} — build it with \`npm run build --prefix server\``,
    );
  }

  const steps: string[] = [];

  // 1. A credential of this harness's own, carrying what #141 made a token able
  //    to say. Falling back is deliberate: minting needs `admin`, and someone
  //    evaluating ADP with a plain repo token should get a working connect and
  //    a sentence about what they did not get, rather than a refusal.
  const minted = await mintToken(harness, flags.model, config.token);
  steps.push(
    minted.token === config.token
      ? "reused the logged-in token — minting needs an admin scope, so this credential names no harness or model"
      : `minted a ${minted.scopes.join(", ")} token carrying harness=${harness.name}${flags.model ? `, model=${flags.model}` : ""}`,
  );

  // 2. The harness's own config, in its own format, at its own path.
  const written = writeMcpServer(root, harness, {
    command: mcp.command,
    args: mcp.args,
    env: { ADP_SERVER_URL: config.serverUrl, ADP_TOKEN: minted.token },
  });
  steps.push(`${written.created ? "wrote" : "updated"} ${path.relative(root, written.file)}`);

  // 3. The client half of #142: the trailer that binds a pushed commit to its
  //    intent, which until now somebody had to type into every commit message.
  const hooks = hooksDir(process.cwd());
  if (hooks) {
    const hook = installHook(hooks);
    steps.push(
      hook.outcome === "foreign"
        ? `left ${path.relative(root, hook.file)} alone — it is not ADP's, so the ADP-Intent trailer is not automatic here`
        : `${hook.outcome} the prepare-commit-msg hook that writes the ADP-Intent trailer`,
    );
  }

  // 4. Recording, on whatever terms this harness allows.
  steps.push(wireRecording(root, harness, config.serverUrl, minted.token, target));

  // 5. Keep the credential out of commits. Everything above wrote a live token
  //    into the working tree, because that is what the harness reads — and the
  //    next `git add -A` would publish it.
  if (excludePaths(process.cwd(), excludedFor(harness))) {
    steps.push("excluded those files from commits in this clone — they hold a live token");
  }

  // 6. The round trip. Everything above wrote a file; this is the only step
  //    that finds out whether any of it is true.
  const proof = await proveRoundTrip(config.serverUrl, minted.token, target, harness.name);

  console.log(`connected ${harness.name} to ${config.serverUrl} for ${target.owner}/${target.repo}`);
  for (const step of steps) console.log(`  · ${step}`);
  console.log(`  ✓ ${proof}`);
  console.log(`  trajectory: ${harness.stream}`);
}

export async function disconnect(argv: string[]): Promise<void> {
  const [name] = argv;
  const harness = name ? findHarness(name) : null;
  if (!harness) throw new Error(`usage: adp disconnect <${harnessNames().join("|")}>`);

  const root = repoRoot(process.cwd());
  if (!root) throw new Error("run this inside a git repository");

  const removed: string[] = [];
  const config = removeMcpServer(root, harness);
  if (config.removed) removed.push(path.relative(root, config.file));

  const launcher = launcherPath(root, harness);
  if (existsSync(launcher)) {
    rmSync(launcher, { force: true });
    removed.push(path.relative(root, launcher));
  }

  const hooks = hooksDir(process.cwd());
  if (hooks) {
    const hook = removeHook(hooks);
    if (hook.removed) removed.push(path.relative(root, hook.file));
  }

  // #237: connect writes the SessionStart hook, so disconnect takes it back
  // out — matched on the command it runs, so a developer's own hooks in the
  // same file are untouched.
  const sessionStart = removeSessionStartHook(root, `./${path.relative(root, launcher)}`);
  if (sessionStart.removed) removed.push(`the ADP hook in ${CLAUDE_SETTINGS}`);

  if (stopWatcher(root, harness)) removed.push(`the transcript watcher for ${harness.name}`);

  if (unexcludePaths(process.cwd(), excludedFor(harness))) removed.push("its entries in .git/info/exclude");

  // The token is not revoked here, and saying so is better than leaving it to
  // be discovered. Revoking needs the admin scope minting needed, the token may
  // be shared with another checkout of the same repository, and a disconnect
  // that silently cut a credential something else was using would be the more
  // surprising of the two behaviours.
  console.log(removed.length ? `disconnected ${harness.name}` : `${harness.name} was not connected here`);
  for (const file of removed) console.log(`  · removed ${file}`);
  if (removed.length) console.log("  · the token itself is left alone — revoke it from the server if it was only for this");
}

/**
 * A credential for this harness, belonging to the person connecting it.
 *
 * **Minted under the caller's own principal, deliberately.** The obvious thing
 * is a fresh principal per harness — `claude-code@alice` — and it produces a
 * token that can reach nothing at all: minting creates an identity and a token
 * and grants no org membership, and every repository route requires the
 * identity to be a live member of the repo's org. There is no REST route that
 * grants one, so a synthetic principal is a dead end rather than a longer road.
 *
 * Reusing the caller's principal is also the more accurate claim. #141 fixed
 * the grain of these fields: `model` on a token says which integration the
 * credential belongs to — "this is the Codex integration's token" — not which
 * model produced an attempt. A per-harness credential held by the developer is
 * exactly that, and the provenance on a signed change then names both the
 * person and the harness rather than a principal that stands for neither.
 *
 * What it is not is the caller's *token*: this one carries `repo:read` and
 * `repo:write` and never `admin`, so what a harness holds cannot mint further
 * credentials even when the developer's own can.
 */
async function mintToken(harness: Harness, model: string | undefined, fallback: string): Promise<MintedToken> {
  try {
    const me = await apiRequest<{ login: string }>("GET", "/api/v3/user");
    const res = await apiRequest<{ token: string; scopes: string[] }>("POST", "/api/adp/tokens", {
      principal: me.login,
      scopes: ["repo:read", "repo:write"],
      harness: harness.name,
      ...(model ? { model } : {}),
    });
    return { token: res.token, scopes: res.scopes };
  } catch (err) {
    // 401/403 on the mint is the ordinary case for someone evaluating ADP
    // alone with a repo token: minting needs `admin`. Refusing the whole
    // connect over the half that needs it would fail exactly the person this
    // command exists for. Anything else is a real failure and is not quietly
    // downgraded to a fallback.
    if (err instanceof ApiError && (err.status === 401 || err.status === 403)) {
      return { token: fallback, scopes: [] };
    }
    throw err;
  }
}

/** The paths this harness's connect writes a token into, as git ignore patterns. */
function excludedFor(harness: Harness): string[] {
  return [`/${harness.configPath.split(path.sep).join("/")}`, "/.adp/"];
}

function launcherPath(root: string, harness: Harness): string {
  return path.join(root, ".adp", `record-${harness.name}`);
}

/**
 * Attach the recorder — differently per harness, because their means differ.
 *
 * Claude Code is the only one that can start it by itself: a `SessionStart`
 * hook is handed the transcript path, which is precisely what `adp-recorder
 * tail` wants, so recording begins when a session does and nobody types
 * anything. The others get a launcher: `wrap` is the honest answer where the
 * harness offers no place to hook in, and a script in the repository is better
 * than a paragraph in a README that has to be retyped correctly.
 */
function wireRecording(
  root: string,
  harness: Harness,
  serverUrl: string,
  token: string,
  target: { owner: string; repo: string },
): string {
  const recorder = recorderBin(installRoot());
  if (!recorder) {
    return "no built recorder found — run `npm run build --prefix recorder`, then connect again to wire recording";
  }
  const repo = `${target.owner}/${target.repo}`;

  const launcher = launcherPath(root, harness);
  mkdirSync(path.dirname(launcher), { recursive: true });
  const body =
    harness.recording === "hook"
      ? `#!/bin/sh
${MARKER}
#
# Claude Code hands a SessionStart hook the transcript path on stdin. That is
# exactly what \`tail\` follows, so recording starts when a session does.
#
# \`--check\` resolves the path and prints it without starting anything, which is
# how \`adp connect\` proves this script before telling anyone it is finished.
# The line below is the step that fails silently when the payload shape moves:
# it finds no path, the hook exits 0, and no session is ever recorded — which
# looks exactly like nothing having happened.
set -e
transcript=$(sed -n 's/.*"transcript_path"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p')
if [ "$1" = "--check" ]; then
  printf '%s\\n' "$transcript"
  exit 0
fi
[ -n "$transcript" ] || exit 0
ADP_SERVER_URL=${shellQuote(serverUrl)} ADP_TOKEN=${shellQuote(token)} \\
  nohup ${shellQuote(process.execPath)} ${shellQuote(recorder)} tail \\
  --repo ${shellQuote(repo)} --harness ${shellQuote(harness.name)} --file "$transcript" \\
  >/dev/null 2>&1 &
exit 0
`
      : `#!/bin/sh
${MARKER}
#
# Run the harness through the recorder. Everything expensive — batching, retry,
# the session lifecycle — happens on this side of the pipe, so the agent pays
# nothing for being recorded.
exec env ADP_SERVER_URL=${shellQuote(serverUrl)} ADP_TOKEN=${shellQuote(token)} \\
  ${shellQuote(process.execPath)} ${shellQuote(recorder)} wrap \\
  --repo ${shellQuote(repo)} --harness ${shellQuote(harness.name)} -- "$@"
`;
  writeFileSync(launcher, body, { mode: 0o755 });
  chmodSync(launcher, 0o755);

  const relative = path.relative(root, launcher);

  // #237: written, not instructed.
  //
  // "Add it as a SessionStart hook in .claude/settings.json" was the last step
  // of a command whose promise is *one* command and then the harness records
  // itself — and it failed silently when skipped, because a session that is not
  // recorded looks exactly like a session that never happened.
  //
  // The reason it was not written before is real and is answered rather than
  // ignored: `.claude/settings.json` may already hold the developer's own
  // hooks, and merging JSON somebody else owns is how connect comes to own it.
  // That is the same risk `.mcp.json` carries, and the answer is the same —
  // ADP owns one entry, recognised by the command it runs, and never the file.
  if (harness.recording === "hook") {
    const written = writeSessionStartHook(root, `./${relative}`);
    proveHook(launcher);
    return `wrote ${relative} and registered it in ${CLAUDE_SETTINGS} — an ordinary session records itself${
      written.created ? "" : " (your other hooks were left alone)"
    }`;
  }

  // The harness has no hook, so nothing in it can start the recorder. `wrap`
  // was the previous answer and is still written, because an explicit
  // invocation is genuinely useful in CI — but it is the mechanism, not the
  // interface: a command the developer types instead of their normal one is
  // capture they perform, and it fails silently the first time they forget.
  const sessions = harness.sessionsDir?.() ?? null;
  if (!sessions) {
    return `wrote ${relative} — run the harness through it: ./${relative} <the usual command>`;
  }
  const watcher = startWatcher(root, harness, recorder, serverUrl, token, repo, sessions);
  return watcher
    ? `wrote ${relative}, and watching ${sessions} — an ordinary session records itself. ` +
        `Stop with \`adp disconnect ${harness.name}\``
    : `wrote ${relative} — run the harness through it: ./${relative} <the usual command>`;
}

/** Where the watcher's pid is kept, so disconnect can stop the one connect started. */
function watcherPidPath(root: string, harness: Harness): string {
  return path.join(root, ".adp", `watch-${harness.name}.pid`);
}

/**
 * Start watching this harness's session directory, in the background.
 *
 * Detached, because it has to outlive the `adp connect` that started it — the
 * whole point is that the developer types nothing further. Its pid is written
 * down so `disconnect` stops exactly the process `connect` started, rather than
 * pattern-matching the process table and hoping.
 *
 * **It does not survive a reboot, and that is stated rather than hidden.**
 * A supervised service is the honest fix and it is a bigger decision than this
 * item: it means deciding whose init system, and it means ADP running when
 * nobody asked it to. Re-running `adp connect` is one command, and connect is
 * already the command that means "set this up".
 */
function startWatcher(
  root: string,
  harness: Harness,
  recorder: string,
  serverUrl: string,
  token: string,
  repo: string,
  sessions: string,
): boolean {
  stopWatcher(root, harness);
  try {
    const child = spawn(
      process.execPath,
      [recorder, "watch", "--repo", repo, "--harness", harness.name, "--sessions", sessions, "--dir", root],
      {
        detached: true,
        stdio: "ignore",
        env: { ...process.env, ADP_SERVER_URL: serverUrl, ADP_TOKEN: token },
      },
    );
    child.unref();
    if (!child.pid) return false;
    mkdirSync(path.dirname(watcherPidPath(root, harness)), { recursive: true });
    writeFileSync(watcherPidPath(root, harness), `${child.pid}\n`);
    return true;
  } catch {
    return false;
  }
}

/** Stop the watcher connect started here, if it is still running. */
function stopWatcher(root: string, harness: Harness): boolean {
  const file = watcherPidPath(root, harness);
  if (!existsSync(file)) return false;
  const pid = Number(readFileSync(file, "utf8").trim());
  rmSync(file, { force: true });
  if (!Number.isInteger(pid) || pid <= 0) return false;
  try {
    // SIGTERM, not SIGKILL: the watcher stops its children the same way, and a
    // transcript that is mid-delivery finishes delivering.
    process.kill(pid, "SIGTERM");
    return true;
  } catch {
    // Already gone — a reboot, or the developer stopped it. Nothing to do, and
    // nothing worth reporting as a failure.
    return false;
  }
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/**
 * Open a session and close it again, with the credential that was just written.
 *
 * The one step that can fail honestly. It is a real session in the repository
 * being connected rather than a health check, because a health check would pass
 * against a server the token cannot write to, in a repository the token cannot
 * see — which are the two failures worth catching. It is closed immediately, so
 * what it leaves behind is one closed session and a `session.start` /
 * `session.close` pair in the operation log: a record that the connection was
 * made, which is a reasonable thing for an audit log to contain.
 */
async function proveRoundTrip(
  serverUrl: string,
  token: string,
  target: { owner: string; repo: string },
  harness: string,
): Promise<string> {
  const base = `${serverUrl}/api/adp/repos/${target.owner}/${target.repo}/sessions`;
  const headers = { Authorization: `Bearer ${token}`, "Content-Type": "application/json" };

  const started = await fetch(base, { method: "POST", headers, body: JSON.stringify({ harness }) });
  if (!started.ok) {
    throw new Error(
      `the configuration was written, but it does not work: opening a session returned HTTP ${started.status} ` +
        `${await started.text()}`,
    );
  }
  const session = (await started.json()) as { id: string };
  const closed = await fetch(`${base}/${session.id}/close`, {
    method: "POST",
    headers,
    body: JSON.stringify({ status: "closed" }),
  });
  if (!closed.ok) {
    throw new Error(`opened session ${session.id} but could not close it: HTTP ${closed.status}`);
  }
  return `verified with a real session (${session.id}), opened and closed`;
}

/**
 * Which ADP repository this checkout is.
 *
 * Read from what `adp init` recorded (#238), not inferred from a git remote.
 * The inference is kept as a last resort so that a checkout set up before this
 * existed keeps working — and when it answers, the answer is written down, so
 * a clone infers at most once and every command after that is immune to the
 * remote being renamed or removed.
 *
 * In companion mode there is no ADP remote to infer from at all: the developer
 * pushes to GitHub and ADP observes, which is why the remote stopped being
 * added unconditionally.
 */
export function resolveRepoTarget(
  root: string,
  serverUrl: string,
  flag: string | undefined,
): { owner: string; repo: string } {
  if (flag) return splitRepo(flag);

  const recorded = loadRepoIdentity(root, serverUrl);
  if (recorded) return { owner: recorded.owner, repo: recorded.repo };

  const inferred = remoteRepo(root, serverUrl);
  if (inferred) {
    saveRepoIdentity(root, { serverUrl, owner: inferred.owner, repo: inferred.repo, mode: "native" });
    return inferred;
  }

  throw new Error(
    `this checkout is not attached to ${serverUrl} — run \`adp init\`, or name the repository ` +
      "with --repo <owner>/<repo>",
  );
}

/**
 * Run the hook the way the harness will, and check it finds the transcript.
 *
 * `connect` already opens and closes a real session to prove the credential,
 * on the reasoning that a config written to the wrong path fails silently and
 * looks exactly like success. The ambient path deserves the same, and this is
 * the step of it that can be wrong: the hook is handed a JSON payload on stdin
 * and has to pull one field out of it. If that stops matching — a renamed key,
 * a reshaped payload — the hook exits 0 having found nothing, no session is
 * ever recorded, and it is indistinguishable from never having been wired.
 *
 * Deliberately not a live capture. Starting a real session here would mean
 * polling for it to appear, which makes `adp connect` fail on a slow machine
 * with a correct setup — the worst outcome available for a first-contact
 * command. `--check` proves the same parsing with no timing in it.
 */
function proveHook(launcher: string): void {
  const transcript = "/tmp/adp-connect-check.jsonl";
  const result = spawnSync("/bin/sh", [launcher, "--check"], {
    input: JSON.stringify({ session_id: "check", transcript_path: transcript }),
    encoding: "utf8",
  });
  if (result.status !== 0 || result.stdout.trim() !== transcript) {
    throw new Error(
      `the hook was written but does not work: given a SessionStart payload it resolved ` +
        `${JSON.stringify(result.stdout.trim())} instead of the transcript path. ` +
        "Nothing would have been recorded, and nothing would have said so.",
    );
  }
}
