#!/usr/bin/env bash
# Generate .env.test at the repo root.
#
#   bash scripts/dev/env.sh [DATABASE_URL]
#
# Normally called by up.sh with the DSN it discovered from the ephemeral
# Postgres, but it stands alone too — pass a DSN to point the test suite at a
# database you brought up yourself, with no Docker involved.
#
# Plain KEY=value lines with no `export`, so it works both as a docker env-file
# and with `set -a; . .env.test; set +a`.
set -euo pipefail

# shellcheck source=scripts/dev/lib.sh
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

DATABASE_URL="${1:-${DATABASE_URL:-$ADP_DEFAULT_DATABASE_URL}}"
ENV_FILE="$ADP_REPO_ROOT/.env.test"

# Under the repo root rather than mktemp, deliberately: a fixed, prefixed,
# gitignored path is one down.sh can remove and verify-clean.sh can assert on.
# A mktemp dir that leaks is invisible until the disk fills.
GIT_ROOT="${GIT_ROOT:-$ADP_REPO_ROOT/.adp-test/git}"
mkdir -p "$GIT_ROOT"

# Fresh per run. The server derives the actual Ed25519 key from this via
# SHA-256 (server/src/core/signing.ts), so any sufficiently random string works
# — but a *fixed* one would mean signatures from an old run verify against a
# new one, quietly hiding a whole class of provenance bug.
SIGNING_KEY="$(openssl rand -hex 32)"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/dev/env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) — do not edit,
# do not commit. Regenerate with 'make up', or remove with 'make down'.
DATABASE_URL=$DATABASE_URL
GIT_ROOT=$GIT_ROOT
SIGNING_KEY=$SIGNING_KEY
PUBLIC_URL=${PUBLIC_URL:-http://localhost:${ADP_SERVER_PORT}}
PORT=${ADP_SERVER_PORT}

# The whole point of the ephemeral stack: with a database guaranteed present,
# a skipped e2e tier is a bug, not a convenience (server/test/require-db.ts).
ADP_REQUIRE_DB=1

# Bookkeeping for down.sh — which compose project this env belongs to.
ADP_TEST_PROJECT=${ADP_TEST_PROJECT:-}
EOF

ok "wrote $ENV_FILE"
info "DATABASE_URL=$DATABASE_URL"
info "GIT_ROOT=$GIT_ROOT"
